# pandas

*pandas* is a Python library for data analysis which provides fast, powerful, flexible and easy to use open source data analysis and manipulation tools. It also provides expressive data structures designed to make working with structured (tabular, multidimensional, potentially heterogeneous) and time series data both easy and intuitive. In pandas, the data table is called DataFrame. Using pandas, you can explore, clean and process your data.  

It offers a number of data exploration, cleaning and transformation operations that are critical in working with data in Python. 

*pandas* build upon *numpy* and *scipy* providing easy-to-use data structures and data manipulation functions with integrated indexing.

The main data structures *pandas* provides are *Series* and *DataFrame*. After a brief introduction to these two data structures and data ingestion, the key features of *pandas* this notebook covers are:
* Generating descriptive statistics on data
* Data cleaning using built in pandas functions
* Frequent data operations for subsetting, filtering, insertion, deletion and aggregation of data
* Merging multiple datasets using DataFrame
* Working with timestamps and time-series data

This notebook is a summary of an introductions to pandas and some of its methods. 

#### Import Libraries
The first step in using different libraries in Python is importing libraries so that it will be accessible for use. You can import the library by its name as it is or using aliases to make its usage easier.

In [1]:
import datetime
current_time = datetime.datetime.now()
current_time.isoformat()

'2022-04-13T09:47:09.564092'

In [2]:
import datetime as dt
current_time = dt.datetime.now()
current_time.isoformat()

'2022-04-13T09:47:09.656843'

In [3]:
# Import the library with alias and print its version
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.__version__

'1.3.4'

There are two major pandas data structures: Series and DataFrames.
* Series: a one-dimensional labeled array-like object that capable of holding any data type and it maps an index to values. 
* DataFrame: a 2-dimensional labeled data structure ( a rectangular table of data) with potentially different data types. It has both  row/s and column/s.

You can import different data files such as Excel, CSV, SAs, SPSS, ...etc to pandas DataFrame.

In [4]:
# Creating Series
s = pd.Series(np.random.randn(5), name="Series1")
s

0   -0.550800
1   -0.170476
2    0.030573
3   -0.018817
4   -1.208114
Name: Series1, dtype: float64

In [5]:
# checking name of the series
s.name

'Series1'

In [6]:
# Creating DataFrame
df1 = pd.DataFrame.from_dict(dict([("A", [1, 2, 3, 4]), ("B", [10, 11, 12, 13])]))
df1.head()

   A   B
0  1  10
1  2  11
2  3  12
3  4  13

In [7]:
df1 = df1.drop(index=[1,3])
df1.head()

   A   B
0  1  10
2  3  12

In [8]:
df1 = df1.reset_index()

df1.head()

   index  A   B
0      0  1  10
1      2  3  12

In [9]:
# Creating another DataFrame
df2 = pd.DataFrame.from_dict(
    dict([("A", [1, 2, 3, 4]), ("B", [10, 11, 12, 13])]),
    orient="index",
    columns=["One", "Two", "Three", "Four"],)
df2.head()

   One  Two  Three  Four
A    1    2      3     4
B   10   11     12    13

In [10]:
# Main DataFrame components
columns = df2.columns
index = df2.index
data = df2.values

In [11]:
columns

Index(['One', 'Two', 'Three', 'Four'], dtype='object')

In [12]:
index

Index(['A', 'B'], dtype='object')

In [13]:
data

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]], dtype=int64)

In [14]:
# Dimension of the DataFrame
df2.shape

(2, 4)

In [15]:
# DataFrame values
df2.values

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]], dtype=int64)

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, A to B
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   One     2 non-null      int64
 1   Two     2 non-null      int64
 2   Three   2 non-null      int64
 3   Four    2 non-null      int64
dtypes: int64(4)
memory usage: 80.0+ bytes

In [17]:
# Associate's Degrees in Science and Engineering Conferred per 1,000 Individuals 18–24 Years Old (Degrees) this a publicly 
#1 Number of S&E Associete degrees receipients of 18 24 years old by state and year
df_assDe = pd.read_excel("se-associates-degrees-per-1000-18-24-year-olds.xlsx", skiprows = [0, 1, 2], 
                         usecols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

df_assDe.head()
df_assDe.columns

Index(['State', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018'],
      dtype='object')

In [18]:
# 2 Number of individuals (18 24 years old) by state and year
df_indv = pd.read_excel("se-associates-degrees-per-1000-18-24-year-olds.xlsx", skiprows = [0, 1, 2], 
                         usecols = [0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38 , 39])
df_indv.columns = ['State', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018']
df_indv.head()

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,United States,27744738.0,28423532.0,28908773.0,29340084.0,29719320.0,29849590.0,30001425.0,30197665.0,30579025.0,30909846.0,31138496.0,31454470.0,31745935.0,31860323.0,31780671.0,31484453.0,31156469.0,30871364.0,30761088.0
1,Alabama,442244.0,447963.0,450657.0,456549.0,457934.0,458170.0,459114.0,462996.0,470431.0,476884.0,479740.0,481821.0,485460.0,486952.0,481029.0,471969.0,462636.0,455854.0,452658.0
2,Alaska,57670.0,61774.0,65287.0,68253.0,71882.0,73591.0,74369.0,74383.0,75206.0,73249.0,75359.0,76122.0,77749.0,79653.0,78581.0,76872.0,74513.0,71961.0,70377.0
3,Arizona,519627.0,536018.0,549407.0,559859.0,571196.0,580341.0,591986.0,605860.0,621451.0,629438.0,635984.0,649306.0,663209.0,670120.0,677544.0,677130.0,677720.0,675845.0,687396.0
4,Arkansas,263749.0,268131.0,272203.0,275122.0,275779.0,274439.0,273882.0,275325.0,278835.0,281953.0,285507.0,289572.0,290876.0,291256.0,290495.0,286985.0,283384.0,280768.0,280578.0

In [19]:
df_indv.shape

(60, 20)

In [20]:
# 3 Degrees per 1000 individuals of 18 24 years old
df_Dper1000I = pd.read_excel("se-associates-degrees-per-1000-18-24-year-olds.xlsx", skiprows = [0, 1, 2], 
                         usecols = [0, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])
df_Dper1000I.columns = ['State', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018']
df_Dper1000I.head()

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,United States,1.389056,1.595790,1.775413,2.144847,2.027166,1.834196,1.661588,1.572473,1.607834,1.756204,1.997881,2.416858,2.670736,2.692942,2.768223,2.877261,2.851157,3.001163,3.202520
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,0.769579,0.858799,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,0.177477,0.477713,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,8.227975,12.852525,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,0.741258,0.816092,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556

In [21]:
#df_Dper1000I['P'] = [a - b for a in df_Dper1000I['2002'] for b in  df_Dper1000I['2000'] for x in df_Dper1000I['State'] if x == "Alabama"]

df_Dper1000I['K'] = df_Dper1000I['2002']- df_Dper1000I['2000']  
df_Dper1000I.head()

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,K
0,United States,1.389056,1.595790,1.775413,2.144847,2.027166,1.834196,1.661588,1.572473,1.607834,...,1.997881,2.416858,2.670736,2.692942,2.768223,2.877261,2.851157,3.001163,3.202520,0.386356
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,...,0.858799,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666,0.288689
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,...,0.477713,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531,-0.052020
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,...,12.852525,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393,0.472841
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,...,0.816092,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556,0.066856

In [22]:
df_Dper1000I['P'] = [0 if x == 'Alabama' else df_Dper1000I['K'] for x in df_Dper1000I['State'] ]
df_Dper1000I.head()

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2011,2012,2013,2014,2015,2016,2017,2018,K,P
0,United States,1.389056,1.595790,1.775413,2.144847,2.027166,1.834196,1.661588,1.572473,1.607834,...,2.416858,2.670736,2.692942,2.768223,2.877261,2.851157,3.001163,3.202520,0.386356,0 0.386356 1 0.288689 2 -0.052020 3...
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,...,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666,0.288689,0
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,...,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531,-0.052020,0 0.386356 1 0.288689 2 -0.052020 3...
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,...,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393,0.472841,0 0.386356 1 0.288689 2 -0.052020 3...
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,...,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556,0.066856,0 0.386356 1 0.288689 2 -0.052020 3...

In [23]:
df_Dper1000I['K'] = df_Dper1000I['2002']- df_Dper1000I['2000'] 
df_Dper1000I.dtypes
#print(df_Dper1000I['P'])
df_Dper1000I.shape

(60, 22)

In [24]:
for x in df_Dper1000I['2000']:
    if x != 1.295665:
        df_Dper1000I['P'] = 'Y'
    else:
        df_Dper1000I['P'] = 'N'
df_Dper1000I.head()
df_Dper1000I.dtypes
for x in df_Dper1000I['State']:
    if x == "United States":
        df_Dper1000I['P'] == 'Y'
        break 
    else:    
        df_Dper1000I['P'] == 'N'
         
df_Dper1000I.head()
# df_Dper1000I['P'] = (df_Dper1000I['py-score'] >= 80) & (df_Dper1000I['js-score'] >= 80)

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2011,2012,2013,2014,2015,2016,2017,2018,K,P
0,United States,1.389056,1.595790,1.775413,2.144847,2.027166,1.834196,1.661588,1.572473,1.607834,...,2.416858,2.670736,2.692942,2.768223,2.877261,2.851157,3.001163,3.202520,0.386356,Y
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,...,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666,0.288689,Y
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,...,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531,-0.052020,Y
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,...,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393,0.472841,Y
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,...,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556,0.066856,Y

In [25]:
#df_Dper1000I['P']  = df_Dper1000I.apply(lambda row: row["2003"] - row['2000'] if row["State"] == 'Alabama' else np.nan, axis=1)
df_Dper1000I.head(52)

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2011,2012,2013,2014,2015,2016,2017,2018,K,P
0,United States,1.389056,1.595790,1.775413,2.144847,2.027166,1.834196,1.661588,1.572473,1.607834,...,2.416858,2.670736,2.692942,2.768223,2.877261,2.851157,3.001163,3.202520,0.386356,Y
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,...,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666,0.288689,Y
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,...,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531,-0.052020,Y
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,...,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393,0.472841,Y
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,...,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556,0.066856,Y
5,California,2.246889,2.150801,2.482296,2.798916,2.576467,2.421829,2.388350,2.407973,2.527423,...,3.830520,4.379885,5.259684,5.963148,6.660418,7.750218,8.617775,10.213075,0.235408,Y
6,Colorado,1.385862,1.664051,1.874592,1.718574,1.527398,1.169972,0.743631,0.617737,0.664584,...,0.892685,0.769913,0.841889,0.816380,0.909904,0.810885,0.792038,0.793428,0.488730,Y
7,Connecticut,0.421977,0.438063,0.566915,0.816285,0.779948,0.869173,0.707644,0.529824,0.530805,...,0.644290,0.702786,0.792473,0.784862,0.921829,0.846045,0.943936,0.954251,0.144939,Y
8,Delaware,1.092781,0.993251,0.818057,0.863705,1.449065,1.420896,1.852311,1.530548,1.083680,...,1.467216,1.553381,2.028265,2.502709,2.505200,2.911721,3.145289,3.460290,-0.274724,Y
9,District of Columbia,0.944119,2.976519,3.314486,2.549198,3.041026,0.551824,2.680930,2.037490,1.675575,...,0.527211,0.296114,0.265998,0.386737,0.418618,0.212106,0.187291,0.269753,2.370367,Y
10,Florida,0.711041,1.501657,1.334936,2.745274,2.261422,2.032335,1.500401,1.252987,1.000493,...,1.086416,1.317676,1.600521,1.861931,1.845050,1.560145,1.656408,1.611008,0.623895,Y
11,Georgia,0.250941,0.317482,0.427336,1.341489,1.473982,1.137916,1.116167,0.917204,0.917885,...,1.308986,1.283611,1.335001,1.351516,1.501212,1.247874,1.271822,1.342113,0.176394,Y
12,Hawaii,1.688651,1.545838,1.508465,2.685242,2.366974,2.190033,1.673144,1.869495,1.166979,...,1.049350,1.513449,1.493819,1.535751,1.253612,1.807653,1.928166,1.938256,-0.180186,Y
13,Idaho,2.983110,3.612737,3.251201,2.786720,2.369202,1.482478,1.202517,1.237471,1.493623,...,1.680618,2.900555,3.264432,3.419390,3.199898,3.417851,3.129822,3.200875,0.268091,Y
14,Illinois,0.413409,0.574557,0.609634,1.388325,1.136962,1.318207,1.135863,1.025422,0.979317,...,1.070957,1.181355,1.171357,1.145338,1.189091,1.044781,1.111135,1.112802,0.196224,Y
15,Indiana,1.184784,1.188786,1.606224,1.690883,1.644112,1.591448,1.499865,1.256453,1.205825,...,1.905063,2.426070,2.590199,2.721086,2.244000,1.251623,1.240598,1.187542,0.421439,Y
16,Iowa,0.638137,1.091433,1.444488,2.493670,2.583479,2.298161,2.215683,2.262686,2.196787,...,3.958978,4.467906,3.578356,3.486903,3.209784,2.927286,2.718192,2.319531,0.806352,Y
17,Kansas,3.376987,3.181887,2.996327,2.970013,1.931023,1.897930,1.578782,1.533916,1.491537,...,1.882657,1.935949,1.516495,2.095713,2.065500,1.731033,1.624874,1.679475,-0.380660,Y
18,Kentucky,1.017020,1.213315,1.560206,1.723689,1.787978,1.574583,1.427058,1.481569,1.197393,...,1.679667,1.527732,1.280540,1.238829,1.568935,1.276247,1.438653,1.335785,0.543186,Y
19,Louisiana,1.054367,1.565924,1.138024,1.198166,1.171073,1.231382,0.802764,0.733001,0.647997,...,0.841680,0.904798,0.889556,0.947822,0.861760,0.671569,0.764131,0.672389,0.083657,Y
20,Maine,0.517038,0.755759,0.917823,0.669438,0.999452,0.531482,0.562439,0.575473,0.716442,...,0.583591,0.550628,0.642975,2.238845,2.730071,2.922654,2.548100,2.511109,0.400785,Y
21,Maryland,0.585615,0.633614,0.649970,0.875330,0.860067,0.976232,0.817641,0.741319,0.811222,...,1.542672,1.638270,1.505016,1.862867,2.101263,2.067552,2.405150,2.544414,0.064354,Y
22,Massachusetts,1.128054,1.065999,1.521237,1.546538,1.636812,1.308634,1.013898,0.993990,0.968825,...,1.342018,1.564609,1.647510,1.796834,1.899773,1.709195,1.999496,1.934671,0.393183,Y
23,Michigan,1.084459,1.378395,1.546594,1.607029,1.539396,1.570162,1.526333,1.556779,1.678760,...,2.470630,2.309108,2.112459,1.940478,1.896018,1.617782,1.622941,1.579102,0.462135,Y
24,Minnesota,1.136484,1.560303,1.742185,2.618614,2.261083,2.128506,1.782958,1.699373,1.717951,...,2.637043,2.779935,2.876910,2.743997,2.801159,2.576491,2.659025,2.679234,0.605701,Y
25,Mississippi,0.960018,1.151014,1.847089,1.510579,1.792413,1.649970,1.329735,1.567614,1.583622,...,2.424822,2.937935,2.483609,2.767154,3.159713,3.350522,3.426134,3.487209,0.887070,Y
26,Missouri,1.218542,1.482026,1.744290,2.726574,2.232518,1.716421,1.428838,1.319793,1.440205,...,1.967240,2.146348,1.999195,1.810668,1.997920,1.940554,1.728079,1.740865,0.525748,Y
27,Montana,1.775766,1.947550,2.284819,2.314257,2.011164,1.591937,1.690872,1.278825,1.647888,...,1.795036,1.930070,1.763527,1.856436,1.560874,1.583039,1.512661,1.310376,0.509053,Y
28,Nebraska,2.512305,3.140595,3.478509,2.715390,2.341995,2.595994,1.947440,1.818555,1.738688,...,1.665506,1.966055,2.087036,1.978843,1.779862,1.567023,1.736721,1.830023,0.966204,Y
29,Nevada,0.543013,0.799024,1.304301,1.402227,1.388384,1.184114,1.188952,1.317396,1.226056,...,2.015853,1.829589,1.870580,2.138141,2.273829,1.902772,1.954593,1.856995,0.761288,Y
30,New Hampshire,2.696378,3.045016,3.041155,2.524723,2.588115,2.164791,1.902801,2.214458,1.954159,...,2.363539,2.493335,2.398733,2.219764,2.191409,2.071502,2.436636,3.210795,0.344776,Y
31,New Jersey,2.123683,1.657073,1.956356,1.956287,1.931516,1.618197,1.456429,1.280909,1.266194,...,1.641449,1.860134,1.801528,2.009817,2.208416,2.374253,2.402753,2.647499,-0.167327,Y
32,New Mexico,1.269599,2.092220,1.417987,1.647714,1.540412,1.517780,1.663144,1.748260,1.601158,...,1.705206,1.988072,2.994224,3.318948,3.749624,3.975398,4.769396,4.583323,0.148388,Y
33,New York,2.229374,2.873911,2.745678,2.983060,2.570917,2.255680,1.905283,1.685865,1.619661,...,2.061595,2.198028,2.549575,2.655086,2.845203,2.937719,3.150219,3.534119,0.516304,Y
34,North Carolina,0.483697,0.720247,1.023764,2.035318,1.907324,1.582817,1.387828,1.067064,0.893874,...,1.435445,1.589760,1.459568,1.481989,1.594797,1.395325,1.540280,1.643570,0.540067,Y
35,North Dakota,0.626968,1.098628,0.913369,1.308788,1.728415,1.031992,0.767513,0.904072,1.142066,...,1.210378,1.053851,1.181058,1.099904,0.822612,0.884083,0.780586,0.861743,0.286402,Y
36,Ohio,1.361757,1.492096,1.800948,2.238631,2.362716,2.005277,1.994055,1.762631,1.918382,...,2.322214,2.398687,2.186759,1.990313,1.988309,1.943258,1.887586,1.959375,0.439191,Y
37,Oklahoma,2.492478,2.689292,2.593247,3.065301,3.078969,3.466340,3.298272,3.400626,3.101524,...,3.991135,4.699162,4.883294,5.081960,5.041048,4.742067,5.232878,5.109566,0.100769,Y
38,Oregon,0.903255,0.850731,1.014575,1.288095,1.387734,1.107461,1.110864,0.861957,0.764965,...,1.492492,1.723595,1.658930,1.715346,1.908376,1.750871,1.875538,1.901141,0.111320,Y
39,Pennsylvania,1.762414,1.927360,2.613230,2.513639,2.450464,2.274290,2.069264,1.974283,1.889799,...,2.185507,2.489427,2.380307,2.343372,2.291412,2.178995,2.198196,2.246868,0.850816,Y
40,Rhode Island,2.612745,2.436585,3.006492,2.680705,2.665555,2.560664,2.380382,2.126569,2.254877,...,2.222700,1.761058,1.542498,1.340357,1.534986,1.417124,1.479487,1.361550,0.393747,Y
41,South Carolina,1.062792,1.095403,1.184476,1.268836,1.082278,1.092391,0.946074,0.864486,0.888553,...,1.001165,1.565361,1.950105,1.728047,1.857858,1.664862,1.506655,1.386092,0.121683,Y
42,South Dakota,2.025407,1.956947,2.598106,3.476650,3.998915,2.374062,1.883261,2.098394,1.884911,...,2.880351,2.613199,2.802280,2.961699,2.840434,3.054893,3.104659,3.428065,0.572699,Y
43,Tennessee,0.508529,0.571664,1.033920,1.184558,1.007693,1.047343,0.956522,0.878031,0.868987,...,0.961037,1.243527,1.038286,1.050162,0.978928,0.702564,0.691349,0.689161,0.525391,Y
44,Texas,1.239980,1.522041,1.474553,1.721863,1.746678,1.618927,1.489945,1.428665,1.447724,...,1.767121,2.018599,2.023163,1.996678,2.218380,2.135722,2.396732,2.408730,0.234572,Y
45,Utah,1.904625,2.130814,2.963527,2.876623,2.696647,2.466906,2.019181,1.968645,1.780484,...,2.178907,2.249272,2.169426,2.261041,2.486240,2.645961,2.790564,2.775673,1.058902,Y
46,Vermont,2.412057,1.903305,2.343621,2.253008,1.877376,1.371129,1.616692,1.132208,0.890718,...,1.631617,1.472444,1.532875,1.528281,1.309729,1.610473,1.409496,1.576935,-0.068436,Y
47,Virginia,1.798677,1.909941,2.299614,2.574407,2.559136,2.556329,2.950660,3.003484,3.800199,...,4.876773,5.419507,5.533492,5.243191,5.580948,5.286133,5.172266,5.264289,0.500938,Y
48,Washington,1.208979,1.677875,2.199291,2.801769,3.224778,2.318108,1.903027,1.710404,1.774570,...,2.427402,2.952903,3.033521,3.155182,3.205162,3.479279,3.708352,3.963824,0.990311,Y
49,West Virginia,0.549108,1.479281,1.569301,1.617864,1.497118,1.433335,0.802597,1.026257,0.944816,...,1.785725,1.588977,2.059256,1.694103,2.300558,2.229174,2.346870,2.486468,1.020194,Y
50,Wisconsin,1.130333,1.508084,1.683739,2.788224,2.642549,2.266868,1.912903,1.761663,1.574559,...,2.396863,2.674979,2.511796,2.222372,1.956355,2.070239,2.004531,2.078784,0.553407,Y
51,Wyoming,4.367857,5.230650,5.524043,5.758984,5.459205,5.415131,5.566158,5.530524,5.738956,...,6.061576,6.095027,6.787060,6.443389,7.809026,7.240018,8.204642,8.745966,1.156185,Y

In [26]:
df_Dper1000I= df_Dper1000I.iloc[:52]
df_Dper1000I.iloc[:55]

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2011,2012,2013,2014,2015,2016,2017,2018,K,P
0,United States,1.389056,1.595790,1.775413,2.144847,2.027166,1.834196,1.661588,1.572473,1.607834,...,2.416858,2.670736,2.692942,2.768223,2.877261,2.851157,3.001163,3.202520,0.386356,Y
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,...,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666,0.288689,Y
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,...,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531,-0.052020,Y
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,...,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393,0.472841,Y
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,...,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556,0.066856,Y
5,California,2.246889,2.150801,2.482296,2.798916,2.576467,2.421829,2.388350,2.407973,2.527423,...,3.830520,4.379885,5.259684,5.963148,6.660418,7.750218,8.617775,10.213075,0.235408,Y
6,Colorado,1.385862,1.664051,1.874592,1.718574,1.527398,1.169972,0.743631,0.617737,0.664584,...,0.892685,0.769913,0.841889,0.816380,0.909904,0.810885,0.792038,0.793428,0.488730,Y
7,Connecticut,0.421977,0.438063,0.566915,0.816285,0.779948,0.869173,0.707644,0.529824,0.530805,...,0.644290,0.702786,0.792473,0.784862,0.921829,0.846045,0.943936,0.954251,0.144939,Y
8,Delaware,1.092781,0.993251,0.818057,0.863705,1.449065,1.420896,1.852311,1.530548,1.083680,...,1.467216,1.553381,2.028265,2.502709,2.505200,2.911721,3.145289,3.460290,-0.274724,Y
9,District of Columbia,0.944119,2.976519,3.314486,2.549198,3.041026,0.551824,2.680930,2.037490,1.675575,...,0.527211,0.296114,0.265998,0.386737,0.418618,0.212106,0.187291,0.269753,2.370367,Y
10,Florida,0.711041,1.501657,1.334936,2.745274,2.261422,2.032335,1.500401,1.252987,1.000493,...,1.086416,1.317676,1.600521,1.861931,1.845050,1.560145,1.656408,1.611008,0.623895,Y
11,Georgia,0.250941,0.317482,0.427336,1.341489,1.473982,1.137916,1.116167,0.917204,0.917885,...,1.308986,1.283611,1.335001,1.351516,1.501212,1.247874,1.271822,1.342113,0.176394,Y
12,Hawaii,1.688651,1.545838,1.508465,2.685242,2.366974,2.190033,1.673144,1.869495,1.166979,...,1.049350,1.513449,1.493819,1.535751,1.253612,1.807653,1.928166,1.938256,-0.180186,Y
13,Idaho,2.983110,3.612737,3.251201,2.786720,2.369202,1.482478,1.202517,1.237471,1.493623,...,1.680618,2.900555,3.264432,3.419390,3.199898,3.417851,3.129822,3.200875,0.268091,Y
14,Illinois,0.413409,0.574557,0.609634,1.388325,1.136962,1.318207,1.135863,1.025422,0.979317,...,1.070957,1.181355,1.171357,1.145338,1.189091,1.044781,1.111135,1.112802,0.196224,Y
15,Indiana,1.184784,1.188786,1.606224,1.690883,1.644112,1.591448,1.499865,1.256453,1.205825,...,1.905063,2.426070,2.590199,2.721086,2.244000,1.251623,1.240598,1.187542,0.421439,Y
16,Iowa,0.638137,1.091433,1.444488,2.493670,2.583479,2.298161,2.215683,2.262686,2.196787,...,3.958978,4.467906,3.578356,3.486903,3.209784,2.927286,2.718192,2.319531,0.806352,Y
17,Kansas,3.376987,3.181887,2.996327,2.970013,1.931023,1.897930,1.578782,1.533916,1.491537,...,1.882657,1.935949,1.516495,2.095713,2.065500,1.731033,1.624874,1.679475,-0.380660,Y
18,Kentucky,1.017020,1.213315,1.560206,1.723689,1.787978,1.574583,1.427058,1.481569,1.197393,...,1.679667,1.527732,1.280540,1.238829,1.568935,1.276247,1.438653,1.335785,0.543186,Y
19,Louisiana,1.054367,1.565924,1.138024,1.198166,1.171073,1.231382,0.802764,0.733001,0.647997,...,0.841680,0.904798,0.889556,0.947822,0.861760,0.671569,0.764131,0.672389,0.083657,Y
20,Maine,0.517038,0.755759,0.917823,0.669438,0.999452,0.531482,0.562439,0.575473,0.716442,...,0.583591,0.550628,0.642975,2.238845,2.730071,2.922654,2.548100,2.511109,0.400785,Y
21,Maryland,0.585615,0.633614,0.649970,0.875330,0.860067,0.976232,0.817641,0.741319,0.811222,...,1.542672,1.638270,1.505016,1.862867,2.101263,2.067552,2.405150,2.544414,0.064354,Y
22,Massachusetts,1.128054,1.065999,1.521237,1.546538,1.636812,1.308634,1.013898,0.993990,0.968825,...,1.342018,1.564609,1.647510,1.796834,1.899773,1.709195,1.999496,1.934671,0.393183,Y
23,Michigan,1.084459,1.378395,1.546594,1.607029,1.539396,1.570162,1.526333,1.556779,1.678760,...,2.470630,2.309108,2.112459,1.940478,1.896018,1.617782,1.622941,1.579102,0.462135,Y
24,Minnesota,1.136484,1.560303,1.742185,2.618614,2.261083,2.128506,1.782958,1.699373,1.717951,...,2.637043,2.779935,2.876910,2.743997,2.801159,2.576491,2.659025,2.679234,0.605701,Y
25,Mississippi,0.960018,1.151014,1.847089,1.510579,1.792413,1.649970,1.329735,1.567614,1.583622,...,2.424822,2.937935,2.483609,2.767154,3.159713,3.350522,3.426134,3.487209,0.887070,Y
26,Missouri,1.218542,1.482026,1.744290,2.726574,2.232518,1.716421,1.428838,1.319793,1.440205,...,1.967240,2.146348,1.999195,1.810668,1.997920,1.940554,1.728079,1.740865,0.525748,Y
27,Montana,1.775766,1.947550,2.284819,2.314257,2.011164,1.591937,1.690872,1.278825,1.647888,...,1.795036,1.930070,1.763527,1.856436,1.560874,1.583039,1.512661,1.310376,0.509053,Y
28,Nebraska,2.512305,3.140595,3.478509,2.715390,2.341995,2.595994,1.947440,1.818555,1.738688,...,1.665506,1.966055,2.087036,1.978843,1.779862,1.567023,1.736721,1.830023,0.966204,Y
29,Nevada,0.543013,0.799024,1.304301,1.402227,1.388384,1.184114,1.188952,1.317396,1.226056,...,2.015853,1.829589,1.870580,2.138141,2.273829,1.902772,1.954593,1.856995,0.761288,Y
30,New Hampshire,2.696378,3.045016,3.041155,2.524723,2.588115,2.164791,1.902801,2.214458,1.954159,...,2.363539,2.493335,2.398733,2.219764,2.191409,2.071502,2.436636,3.210795,0.344776,Y
31,New Jersey,2.123683,1.657073,1.956356,1.956287,1.931516,1.618197,1.456429,1.280909,1.266194,...,1.641449,1.860134,1.801528,2.009817,2.208416,2.374253,2.402753,2.647499,-0.167327,Y
32,New Mexico,1.269599,2.092220,1.417987,1.647714,1.540412,1.517780,1.663144,1.748260,1.601158,...,1.705206,1.988072,2.994224,3.318948,3.749624,3.975398,4.769396,4.583323,0.148388,Y
33,New York,2.229374,2.873911,2.745678,2.983060,2.570917,2.255680,1.905283,1.685865,1.619661,...,2.061595,2.198028,2.549575,2.655086,2.845203,2.937719,3.150219,3.534119,0.516304,Y
34,North Carolina,0.483697,0.720247,1.023764,2.035318,1.907324,1.582817,1.387828,1.067064,0.893874,...,1.435445,1.589760,1.459568,1.481989,1.594797,1.395325,1.540280,1.643570,0.540067,Y
35,North Dakota,0.626968,1.098628,0.913369,1.308788,1.728415,1.031992,0.767513,0.904072,1.142066,...,1.210378,1.053851,1.181058,1.099904,0.822612,0.884083,0.780586,0.861743,0.286402,Y
36,Ohio,1.361757,1.492096,1.800948,2.238631,2.362716,2.005277,1.994055,1.762631,1.918382,...,2.322214,2.398687,2.186759,1.990313,1.988309,1.943258,1.887586,1.959375,0.439191,Y
37,Oklahoma,2.492478,2.689292,2.593247,3.065301,3.078969,3.466340,3.298272,3.400626,3.101524,...,3.991135,4.699162,4.883294,5.081960,5.041048,4.742067,5.232878,5.109566,0.100769,Y
38,Oregon,0.903255,0.850731,1.014575,1.288095,1.387734,1.107461,1.110864,0.861957,0.764965,...,1.492492,1.723595,1.658930,1.715346,1.908376,1.750871,1.875538,1.901141,0.111320,Y
39,Pennsylvania,1.762414,1.927360,2.613230,2.513639,2.450464,2.274290,2.069264,1.974283,1.889799,...,2.185507,2.489427,2.380307,2.343372,2.291412,2.178995,2.198196,2.246868,0.850816,Y
40,Rhode Island,2.612745,2.436585,3.006492,2.680705,2.665555,2.560664,2.380382,2.126569,2.254877,...,2.222700,1.761058,1.542498,1.340357,1.534986,1.417124,1.479487,1.361550,0.393747,Y
41,South Carolina,1.062792,1.095403,1.184476,1.268836,1.082278,1.092391,0.946074,0.864486,0.888553,...,1.001165,1.565361,1.950105,1.728047,1.857858,1.664862,1.506655,1.386092,0.121683,Y
42,South Dakota,2.025407,1.956947,2.598106,3.476650,3.998915,2.374062,1.883261,2.098394,1.884911,...,2.880351,2.613199,2.802280,2.961699,2.840434,3.054893,3.104659,3.428065,0.572699,Y
43,Tennessee,0.508529,0.571664,1.033920,1.184558,1.007693,1.047343,0.956522,0.878031,0.868987,...,0.961037,1.243527,1.038286,1.050162,0.978928,0.702564,0.691349,0.689161,0.525391,Y
44,Texas,1.239980,1.522041,1.474553,1.721863,1.746678,1.618927,1.489945,1.428665,1.447724,...,1.767121,2.018599,2.023163,1.996678,2.218380,2.135722,2.396732,2.408730,0.234572,Y
45,Utah,1.904625,2.130814,2.963527,2.876623,2.696647,2.466906,2.019181,1.968645,1.780484,...,2.178907,2.249272,2.169426,2.261041,2.486240,2.645961,2.790564,2.775673,1.058902,Y
46,Vermont,2.412057,1.903305,2.343621,2.253008,1.877376,1.371129,1.616692,1.132208,0.890718,...,1.631617,1.472444,1.532875,1.528281,1.309729,1.610473,1.409496,1.576935,-0.068436,Y
47,Virginia,1.798677,1.909941,2.299614,2.574407,2.559136,2.556329,2.950660,3.003484,3.800199,...,4.876773,5.419507,5.533492,5.243191,5.580948,5.286133,5.172266,5.264289,0.500938,Y
48,Washington,1.208979,1.677875,2.199291,2.801769,3.224778,2.318108,1.903027,1.710404,1.774570,...,2.427402,2.952903,3.033521,3.155182,3.205162,3.479279,3.708352,3.963824,0.990311,Y
49,West Virginia,0.549108,1.479281,1.569301,1.617864,1.497118,1.433335,0.802597,1.026257,0.944816,...,1.785725,1.588977,2.059256,1.694103,2.300558,2.229174,2.346870,2.486468,1.020194,Y
50,Wisconsin,1.130333,1.508084,1.683739,2.788224,2.642549,2.266868,1.912903,1.761663,1.574559,...,2.396863,2.674979,2.511796,2.222372,1.956355,2.070239,2.004531,2.078784,0.553407,Y
51,Wyoming,4.367857,5.230650,5.524043,5.758984,5.459205,5.415131,5.566158,5.530524,5.738956,...,6.061576,6.095027,6.787060,6.443389,7.809026,7.240018,8.204642,8.745966,1.156185,Y

In [27]:
df_Dper1000I = df_Dper1000I.dropna()
df_Dper1000I.iloc[:52]

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2011,2012,2013,2014,2015,2016,2017,2018,K,P
0,United States,1.389056,1.595790,1.775413,2.144847,2.027166,1.834196,1.661588,1.572473,1.607834,...,2.416858,2.670736,2.692942,2.768223,2.877261,2.851157,3.001163,3.202520,0.386356,Y
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,...,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666,0.288689,Y
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,...,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531,-0.052020,Y
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,...,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393,0.472841,Y
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,...,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556,0.066856,Y
5,California,2.246889,2.150801,2.482296,2.798916,2.576467,2.421829,2.388350,2.407973,2.527423,...,3.830520,4.379885,5.259684,5.963148,6.660418,7.750218,8.617775,10.213075,0.235408,Y
6,Colorado,1.385862,1.664051,1.874592,1.718574,1.527398,1.169972,0.743631,0.617737,0.664584,...,0.892685,0.769913,0.841889,0.816380,0.909904,0.810885,0.792038,0.793428,0.488730,Y
7,Connecticut,0.421977,0.438063,0.566915,0.816285,0.779948,0.869173,0.707644,0.529824,0.530805,...,0.644290,0.702786,0.792473,0.784862,0.921829,0.846045,0.943936,0.954251,0.144939,Y
8,Delaware,1.092781,0.993251,0.818057,0.863705,1.449065,1.420896,1.852311,1.530548,1.083680,...,1.467216,1.553381,2.028265,2.502709,2.505200,2.911721,3.145289,3.460290,-0.274724,Y
9,District of Columbia,0.944119,2.976519,3.314486,2.549198,3.041026,0.551824,2.680930,2.037490,1.675575,...,0.527211,0.296114,0.265998,0.386737,0.418618,0.212106,0.187291,0.269753,2.370367,Y
10,Florida,0.711041,1.501657,1.334936,2.745274,2.261422,2.032335,1.500401,1.252987,1.000493,...,1.086416,1.317676,1.600521,1.861931,1.845050,1.560145,1.656408,1.611008,0.623895,Y
11,Georgia,0.250941,0.317482,0.427336,1.341489,1.473982,1.137916,1.116167,0.917204,0.917885,...,1.308986,1.283611,1.335001,1.351516,1.501212,1.247874,1.271822,1.342113,0.176394,Y
12,Hawaii,1.688651,1.545838,1.508465,2.685242,2.366974,2.190033,1.673144,1.869495,1.166979,...,1.049350,1.513449,1.493819,1.535751,1.253612,1.807653,1.928166,1.938256,-0.180186,Y
13,Idaho,2.983110,3.612737,3.251201,2.786720,2.369202,1.482478,1.202517,1.237471,1.493623,...,1.680618,2.900555,3.264432,3.419390,3.199898,3.417851,3.129822,3.200875,0.268091,Y
14,Illinois,0.413409,0.574557,0.609634,1.388325,1.136962,1.318207,1.135863,1.025422,0.979317,...,1.070957,1.181355,1.171357,1.145338,1.189091,1.044781,1.111135,1.112802,0.196224,Y
15,Indiana,1.184784,1.188786,1.606224,1.690883,1.644112,1.591448,1.499865,1.256453,1.205825,...,1.905063,2.426070,2.590199,2.721086,2.244000,1.251623,1.240598,1.187542,0.421439,Y
16,Iowa,0.638137,1.091433,1.444488,2.493670,2.583479,2.298161,2.215683,2.262686,2.196787,...,3.958978,4.467906,3.578356,3.486903,3.209784,2.927286,2.718192,2.319531,0.806352,Y
17,Kansas,3.376987,3.181887,2.996327,2.970013,1.931023,1.897930,1.578782,1.533916,1.491537,...,1.882657,1.935949,1.516495,2.095713,2.065500,1.731033,1.624874,1.679475,-0.380660,Y
18,Kentucky,1.017020,1.213315,1.560206,1.723689,1.787978,1.574583,1.427058,1.481569,1.197393,...,1.679667,1.527732,1.280540,1.238829,1.568935,1.276247,1.438653,1.335785,0.543186,Y
19,Louisiana,1.054367,1.565924,1.138024,1.198166,1.171073,1.231382,0.802764,0.733001,0.647997,...,0.841680,0.904798,0.889556,0.947822,0.861760,0.671569,0.764131,0.672389,0.083657,Y
20,Maine,0.517038,0.755759,0.917823,0.669438,0.999452,0.531482,0.562439,0.575473,0.716442,...,0.583591,0.550628,0.642975,2.238845,2.730071,2.922654,2.548100,2.511109,0.400785,Y
21,Maryland,0.585615,0.633614,0.649970,0.875330,0.860067,0.976232,0.817641,0.741319,0.811222,...,1.542672,1.638270,1.505016,1.862867,2.101263,2.067552,2.405150,2.544414,0.064354,Y
22,Massachusetts,1.128054,1.065999,1.521237,1.546538,1.636812,1.308634,1.013898,0.993990,0.968825,...,1.342018,1.564609,1.647510,1.796834,1.899773,1.709195,1.999496,1.934671,0.393183,Y
23,Michigan,1.084459,1.378395,1.546594,1.607029,1.539396,1.570162,1.526333,1.556779,1.678760,...,2.470630,2.309108,2.112459,1.940478,1.896018,1.617782,1.622941,1.579102,0.462135,Y
24,Minnesota,1.136484,1.560303,1.742185,2.618614,2.261083,2.128506,1.782958,1.699373,1.717951,...,2.637043,2.779935,2.876910,2.743997,2.801159,2.576491,2.659025,2.679234,0.605701,Y
25,Mississippi,0.960018,1.151014,1.847089,1.510579,1.792413,1.649970,1.329735,1.567614,1.583622,...,2.424822,2.937935,2.483609,2.767154,3.159713,3.350522,3.426134,3.487209,0.887070,Y
26,Missouri,1.218542,1.482026,1.744290,2.726574,2.232518,1.716421,1.428838,1.319793,1.440205,...,1.967240,2.146348,1.999195,1.810668,1.997920,1.940554,1.728079,1.740865,0.525748,Y
27,Montana,1.775766,1.947550,2.284819,2.314257,2.011164,1.591937,1.690872,1.278825,1.647888,...,1.795036,1.930070,1.763527,1.856436,1.560874,1.583039,1.512661,1.310376,0.509053,Y
28,Nebraska,2.512305,3.140595,3.478509,2.715390,2.341995,2.595994,1.947440,1.818555,1.738688,...,1.665506,1.966055,2.087036,1.978843,1.779862,1.567023,1.736721,1.830023,0.966204,Y
29,Nevada,0.543013,0.799024,1.304301,1.402227,1.388384,1.184114,1.188952,1.317396,1.226056,...,2.015853,1.829589,1.870580,2.138141,2.273829,1.902772,1.954593,1.856995,0.761288,Y
30,New Hampshire,2.696378,3.045016,3.041155,2.524723,2.588115,2.164791,1.902801,2.214458,1.954159,...,2.363539,2.493335,2.398733,2.219764,2.191409,2.071502,2.436636,3.210795,0.344776,Y
31,New Jersey,2.123683,1.657073,1.956356,1.956287,1.931516,1.618197,1.456429,1.280909,1.266194,...,1.641449,1.860134,1.801528,2.009817,2.208416,2.374253,2.402753,2.647499,-0.167327,Y
32,New Mexico,1.269599,2.092220,1.417987,1.647714,1.540412,1.517780,1.663144,1.748260,1.601158,...,1.705206,1.988072,2.994224,3.318948,3.749624,3.975398,4.769396,4.583323,0.148388,Y
33,New York,2.229374,2.873911,2.745678,2.983060,2.570917,2.255680,1.905283,1.685865,1.619661,...,2.061595,2.198028,2.549575,2.655086,2.845203,2.937719,3.150219,3.534119,0.516304,Y
34,North Carolina,0.483697,0.720247,1.023764,2.035318,1.907324,1.582817,1.387828,1.067064,0.893874,...,1.435445,1.589760,1.459568,1.481989,1.594797,1.395325,1.540280,1.643570,0.540067,Y
35,North Dakota,0.626968,1.098628,0.913369,1.308788,1.728415,1.031992,0.767513,0.904072,1.142066,...,1.210378,1.053851,1.181058,1.099904,0.822612,0.884083,0.780586,0.861743,0.286402,Y
36,Ohio,1.361757,1.492096,1.800948,2.238631,2.362716,2.005277,1.994055,1.762631,1.918382,...,2.322214,2.398687,2.186759,1.990313,1.988309,1.943258,1.887586,1.959375,0.439191,Y
37,Oklahoma,2.492478,2.689292,2.593247,3.065301,3.078969,3.466340,3.298272,3.400626,3.101524,...,3.991135,4.699162,4.883294,5.081960,5.041048,4.742067,5.232878,5.109566,0.100769,Y
38,Oregon,0.903255,0.850731,1.014575,1.288095,1.387734,1.107461,1.110864,0.861957,0.764965,...,1.492492,1.723595,1.658930,1.715346,1.908376,1.750871,1.875538,1.901141,0.111320,Y
39,Pennsylvania,1.762414,1.927360,2.613230,2.513639,2.450464,2.274290,2.069264,1.974283,1.889799,...,2.185507,2.489427,2.380307,2.343372,2.291412,2.178995,2.198196,2.246868,0.850816,Y
40,Rhode Island,2.612745,2.436585,3.006492,2.680705,2.665555,2.560664,2.380382,2.126569,2.254877,...,2.222700,1.761058,1.542498,1.340357,1.534986,1.417124,1.479487,1.361550,0.393747,Y
41,South Carolina,1.062792,1.095403,1.184476,1.268836,1.082278,1.092391,0.946074,0.864486,0.888553,...,1.001165,1.565361,1.950105,1.728047,1.857858,1.664862,1.506655,1.386092,0.121683,Y
42,South Dakota,2.025407,1.956947,2.598106,3.476650,3.998915,2.374062,1.883261,2.098394,1.884911,...,2.880351,2.613199,2.802280,2.961699,2.840434,3.054893,3.104659,3.428065,0.572699,Y
43,Tennessee,0.508529,0.571664,1.033920,1.184558,1.007693,1.047343,0.956522,0.878031,0.868987,...,0.961037,1.243527,1.038286,1.050162,0.978928,0.702564,0.691349,0.689161,0.525391,Y
44,Texas,1.239980,1.522041,1.474553,1.721863,1.746678,1.618927,1.489945,1.428665,1.447724,...,1.767121,2.018599,2.023163,1.996678,2.218380,2.135722,2.396732,2.408730,0.234572,Y
45,Utah,1.904625,2.130814,2.963527,2.876623,2.696647,2.466906,2.019181,1.968645,1.780484,...,2.178907,2.249272,2.169426,2.261041,2.486240,2.645961,2.790564,2.775673,1.058902,Y
46,Vermont,2.412057,1.903305,2.343621,2.253008,1.877376,1.371129,1.616692,1.132208,0.890718,...,1.631617,1.472444,1.532875,1.528281,1.309729,1.610473,1.409496,1.576935,-0.068436,Y
47,Virginia,1.798677,1.909941,2.299614,2.574407,2.559136,2.556329,2.950660,3.003484,3.800199,...,4.876773,5.419507,5.533492,5.243191,5.580948,5.286133,5.172266,5.264289,0.500938,Y
48,Washington,1.208979,1.677875,2.199291,2.801769,3.224778,2.318108,1.903027,1.710404,1.774570,...,2.427402,2.952903,3.033521,3.155182,3.205162,3.479279,3.708352,3.963824,0.990311,Y
49,West Virginia,0.549108,1.479281,1.569301,1.617864,1.497118,1.433335,0.802597,1.026257,0.944816,...,1.785725,1.588977,2.059256,1.694103,2.300558,2.229174,2.346870,2.486468,1.020194,Y
50,Wisconsin,1.130333,1.508084,1.683739,2.788224,2.642549,2.266868,1.912903,1.761663,1.574559,...,2.396863,2.674979,2.511796,2.222372,1.956355,2.070239,2.004531,2.078784,0.553407,Y
51,Wyoming,4.367857,5.230650,5.524043,5.758984,5.459205,5.415131,5.566158,5.530524,5.738956,...,6.061576,6.095027,6.787060,6.443389,7.809026,7.240018,8.204642,8.745966,1.156185,Y

In [28]:
df_Dper1000I = df_Dper1000I.iloc[1:54]

In [29]:
df_Dper1000I.shape

(51, 22)

In [30]:
df_Dper1000I.index

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
            18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
            35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51],
           dtype='int64')

In [31]:
df_Dper1000I.dtypes

State     object
2000     float64
2001     float64
2002     float64
2003     float64
2004     float64
2005     float64
2006     float64
2007     float64
2008     float64
2009     float64
2010     float64
2011     float64
2012     float64
2013     float64
2014     float64
2015     float64
2016     float64
2017     float64
2018     float64
K        float64
P         object
dtype: object

In [32]:
df_Dper1000I.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51 entries, 1 to 51
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   51 non-null     object
 1   2000    51 non-null     float64
 2   2001    51 non-null     float64
 3   2002    51 non-null     float64
 4   2003    51 non-null     float64
 5   2004    51 non-null     float64
 6   2005    51 non-null     float64
 7   2006    51 non-null     float64
 8   2007    51 non-null     float64
 9   2008    51 non-null     float64
 10  2009    51 non-null     float64
 11  2010    51 non-null     float64
 12  2011    51 non-null     float64
 13  2012    51 non-null     float64
 14  2013    51 non-null     float64
 15  2014    51 non-null     float64
 16  2015    51 non-null     float64
 17  2016    51 non-null     float64
 18  2017    51 non-null     float64
 19  2018    51 non-null     float64
 20  K       51 non-null     float64
 21  P       51 non-null     object
dtypes: float64(20), object(2)
memory usage: 9.2+ KB

In [33]:
df_Dper1000I.describe(include = 'all')

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2011,2012,2013,2014,2015,2016,2017,2018,K,P
count,51,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,...,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51
unique,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
top,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51
mean,NaN,1.395969,1.641068,1.829406,2.089938,2.014794,1.741067,1.614753,1.533752,1.532981,...,2.227446,2.398750,2.353661,2.381664,2.425209,2.321685,2.389000,2.440515,0.433437,NaN
std,NaN,0.875280,0.952092,0.980127,0.893737,0.867600,0.824333,0.832064,0.856646,0.971688,...,2.476779,2.622491,2.073287,1.859088,1.793678,1.691515,1.758781,1.883390,0.445743,NaN
min,NaN,0.052020,0.000000,0.000000,0.669438,0.514732,0.271772,0.430287,0.215103,0.186155,...,0.527211,0.296114,0.265998,0.386737,0.418618,0.212106,0.187291,0.269753,-0.380660,NaN
25%,NaN,0.698650,1.078716,1.161250,1.395276,1.485550,1.207748,1.109760,0.955597,0.905879,...,1.229187,1.395060,1.397285,1.416752,1.518099,1.335786,1.424074,1.338949,0.146663,NaN
50%,NaN,1.184784,1.508084,1.606224,2.035318,1.907324,1.591448,1.500401,1.428665,1.440205,...,1.705206,1.860134,1.950105,1.978843,1.997920,1.902772,1.928166,1.934671,0.421439,NaN
75%,NaN,1.851651,1.952249,2.412959,2.700316,2.565026,2.261274,1.909093,1.844025,1.756629,...,2.342877,2.491381,2.530685,2.688086,2.765615,2.917187,2.754378,2.988274,0.563053,NaN
max,NaN,4.367857,5.230650,5.524043,5.758984,5.459205,5.415131,5.566158,5.530524,5.738956,...,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,8.617775,10.213075,2.370367,NaN

There are several commands to work on data of *pandas* dataframe such as subsetting, grouping, and merging.

In [34]:
state = df_Dper1000I['State']

In [35]:
state.head()

1       Alabama
2        Alaska
3       Arizona
4      Arkansas
5    California
Name: State, dtype: object

In [36]:
state.tail()

47         Virginia
48       Washington
49    West Virginia
50        Wisconsin
51          Wyoming
Name: State, dtype: object

In [37]:
type(df_Dper1000I)

pandas.core.frame.DataFrame

In [38]:
type(state)

pandas.core.series.Series

In [39]:
#df_Dper1000I.set_index('State', inplace = True)
df_Dper1000I.head()

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2011,2012,2013,2014,2015,2016,2017,2018,K,P
1,Alabama,1.295665,1.428689,1.584354,1.938456,1.629056,1.385948,1.108657,0.771065,0.814147,...,1.019051,1.046430,0.975455,0.914706,0.904720,0.737081,0.651524,0.545666,0.288689,Y
2,Alaska,0.052020,0.000000,0.000000,0.908385,0.514732,0.271772,0.430287,0.215103,0.186155,...,1.247997,0.977505,1.205228,1.005332,0.741492,0.724706,0.833785,0.511531,-0.052020,Y
3,Arizona,1.518397,1.858147,1.991238,2.372026,2.652329,2.365850,2.187552,2.469217,4.257777,...,17.843667,18.761808,13.842297,11.919521,10.029093,7.814437,6.417152,5.004393,0.472841,Y
4,Arkansas,0.686259,0.607912,0.753114,1.046808,0.790488,0.783416,0.828824,0.773631,0.613266,...,0.618154,0.587879,0.638613,0.691922,0.735230,0.635181,0.683839,0.976556,0.066856,Y
5,California,2.246889,2.150801,2.482296,2.798916,2.576467,2.421829,2.388350,2.407973,2.527423,...,3.830520,4.379885,5.259684,5.963148,6.660418,7.750218,8.617775,10.213075,0.235408,Y

In [40]:
df_Dper1000I['2018'].mean()

2.4405146765648635

In [41]:
df_Dper1000I['2018']>df_Dper1000I['2018'].mean()

1     False
2     False
3      True
4     False
5      True
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22    False
23    False
24     True
25     True
26    False
27    False
28    False
29    False
30     True
31     True
32     True
33     True
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42     True
43    False
44    False
45     True
46    False
47     True
48     True
49     True
50    False
51     True
Name: 2018, dtype: bool

In [42]:
from bs4 import BeautifulSoup
# Python 3.x
from urllib.request import urlopen, urlretrieve, quote
from urllib.parse import urljoin

#url = 'https://www.rbi.org.in/Scripts/bs_viewcontent.aspx?Id=2009/'

url = 'https://ncses.nsf.gov/pubs/nsf21303#data-tables/nsf21303-tab002.xlxs'

In [43]:
#soup

In [44]:

df = pd.read_excel('https://ncses.nsf.gov/pubs/nsf21303/assets/data-tables/tables/nsf21303-tab002.xlsx', index_col=0)

In [45]:
import requests, os
import http.client

http.client.HTTPConnection._http_vsn = 10
http.client.HTTPConnection._http_vsn_str = 'HTTP/1.0'

url="https://ncses.nsf.gov/pubs/nsf21303#data-tables"

print("Downloading...")
resp = requests.get(url)
with open('nsf21303-tab002.xlsx', 'wb') as output:
    output.write(resp.content)
print("Done!")

Downloading...
Done!

In [46]:
df = pd.read_excel("https://ncses.nsf.gov/pubs/nsf21303/assets/data-tables/tables/nsf21303-tab001.xlsx", skiprows = [0, 1, 2], usecols= [0, 1, 3, 5])

In [47]:
df.head()

,Company and financial information,All companies,1–4 employees,5–9 employees
0,Total R&D cost,6655717.0,3525771.0,3129946.0
1,"R&D for salaries, wages, and fringe benefits",3656750.0,1895125.0,1761625.0
2,R&D for expensed machinery and equipment (not ...,256952.0,153000.0,103952.0
3,R&D for materials and supplies,583126.0,319901.0,263224.0
4,R&D for payments to business partners for coll...,361014.0,228498.0,132516.0

In [48]:
df.columns

Index(['Company and financial information', 'All companies', '1–4 employees',
       '5–9 employees'],
      dtype='object')